name: Unit tests for data validation scripts

on:
  pull_request:
  push:
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: test validate dn format
      run: bin/test_validate_dn_format.py
